set nocompatible	" Vim mode vs vi mode
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set shiftwidth=4
set showmatch		" Highlight closing ), >, }, ], etc...
set ruler			" Show row,col in cmd line
set hlsearch		" Keep previous search highlighted

set ignorecase		" Ignore case in searches
set smartcase		" Don't ignore case if search string contains uppercase letters
set number			" Display line numbers
set nobackup		" No backup files
syntax on

if has("gui_running")
    set lines=45
    set columns=100
    behave mswin
    set guioptions -=t	" No tearoff in menus
    set confirm			" Give confirm popup if quit w/o saving changes
    set wildmenu
    set wildmode=list:longest
endif

" clear out search buffer easier
nmap <silent> ,/ :let @/=""<CR>

" Change cwd to file we are currently editing
autocmd BufEnter * cd %:p:h

" Enable lint checking for PHP files
set makeprg=php\ -l\ %
set errorformat=%m\ in\ %f\ on\ line\ %l

let php_parent_error_close=1

" If we are using Javascript, we need 2 spaces indents and not tabs
autocmd FileType javascript set sw=2
autocmd FileType javascript set ts=2
autocmd FileType javascript set sts=2

" Ditto for HTML
autocmd FileType html set sw=2
autocmd FileType html set ts=2
autocmd FileType html set sts=2

" The rest of these options are from mswin.vim to make Vim behave more like
" Windows.
set backspace=indent,eol,start whichwrap+=<,>,[,]
" backspace in Visual mode deletes selection
vnoremap <BS> d
" CTRL-X is Cut
vnoremap <C-X> "+x
" CTRL-C is Copy
vnoremap <C-C> "+y
" CTRL-V is Paste
map <C-V> "+gP
cmap <C-V>	<C-R>+

" Pasting blockwise and linewise selections is not possible in Insert and
" Visual mode without the +virtualedit feature.  They are pasted as if they
" were characterwise instead.
" Uses the paste.vim autoload script.

exe 'inoremap <script> <C-V>' paste#paste_cmd['i']
exe 'vnoremap <script> <C-V>' paste#paste_cmd['v']

" Use CTRL-Q to do what CTRL-V used to do
noremap <C-Q>		<C-V>

" Use CTRL-S for saving, also in Insert mode
noremap <C-S>		:update<CR>
vnoremap <C-S>		<C-C>:update<CR>
inoremap <C-S>		<C-O>:update<CR>

" CTRL-Z is Undo; not in cmdline though
noremap <C-Z> u
inoremap <C-Z> <C-O>u

" CTRL-Y is Redo (although not repeat); not in cmdline though
" Commented out b/c it clashes with zencoding plugin
" noremap <C-Y> <C-R>
" inoremap <C-Y> <C-O><C-R>

" CTRL-A is Select all
noremap <C-A> gggH<C-O>G
inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
cnoremap <C-A> <C-C>gggH<C-O>G
onoremap <C-A> <C-C>gggH<C-O>G
snoremap <C-A> <C-C>gggH<C-O>G
xnoremap <C-A> <C-C>ggVG

" CTRL-Tab is Next window
noremap <C-Tab> <C-W>w
inoremap <C-Tab> <C-O><C-W>w
cnoremap <C-Tab> <C-C><C-W>w
onoremap <C-Tab> <C-C><C-W>w

" https://github.com/tpope/vim-pathogen
execute pathogen#infect()

"https://github.com/bling/vim-airline
"let g:airline_theme=''
set laststatus=2

" https://github.com/scrooloose/nerdtree
map <C-t> :NERDTreeToggle<CR>

" https://github.com/altercation/vim-colors-solarized
if !has("gui_running")
    set t_Co=256
    set background=dark
    let g:solarized_termcolors=256
    colorscheme solarized
endif
